### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by Mokashaa** [Mokashaa/ASUMobiCarG50#10]
you should learn how to use arduino board , create your own example ,compile and test it on proteus ISIS

**Comment by ganzourii** [comment]
I recommend this playlist .. [Link](https://www.youtube.com/playlist?list=PLGs0VKk2DiYx6CMdOQR_hmJ2NbB4mZQn-l) 

And the arduino site reference to know more about functions and libraries 
[Link](https://www.arduino.cc/reference/en/)

**Comment by salma97** [comment]
**Arduino Library for Proteus** : [https://www.theengineeringprojects.com/2015/12/arduino-uno-library-proteus.html](url)
**coding the Arduino on Proteus** : [https://www.theengineeringprojects.com/2015/10/hex-file-arduino.html](url)

**Comment by DohaMustafa** [comment]
Git and GitHub introduction :100: 
 https://www.youtube.com/watch?v=BCQHnlnPusY&index=1&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV

**Comment by DohaMustafa** [comment]
Projects Examples using arduino: https://create.arduino.cc/projecthub/attari/getting-started-with-arduino-genuino-101-b666d6

**Comment by FatemaMubarak** [comment]
**Tutorials Proteus for beginners :** https://www.youtube.com/watch?v=ZX00tEko1_4
**Proteus Libraries :** https://www.theengineeringprojects.com/2015/12/arduino-library-proteus-simulation.html
**Tutorial on How to Simulate Arduino Program With Proteus :** https://www.youtube.com/watch?v=fK5oI1XfDYI    https://www.youtube.com/watch?v=-8bJT973yv0
