### ISSUE TITLE
Obstacles Avoiding

### ISSUE THREAD

**Issue by Mokashaa** [Mokashaa/ASUMobiCarG50#14]
You should present an obstacles avoiding technique

**Comment by Salmahossam97** [comment]
we can fix an ultrasonic sensor on a rotating stand at the front of the car  that if it detects some obstacle it should check both right and left directions and goes to the obstacle-free one , we will need to design a stand with a servo motor for rotation

**Comment by mariamelsaayed** [comment]
[ultrasonic.docx](https://github.com/Mokashaa/ASUMobiCarG50/files/1799353/ultrasonic.docx)

1st attempt for ultrasonic sensor for obstacle avoiding using new ping library

**Comment by salma97** [comment]
3 options are available for obstacle avoidance:
1- The use of IR sensors at the front and the back of the Car.
2- The use of ultrasonic sensor without servo motor but it may not be very efficient 
3- The use of ultrasonic sensor with servo motor where the motor keeps rotating right and left checking for obstacles
 
for option 2, continuing on @mariamelsaayed 's code, the car code will be put in an 'else' branch.
for option 3, i think it would have been useful if the car was moving on it's own, when the ultrasonic sensor finds an obstacle the car would stop and we'd give an order to the servo to rotate right/left so the car would go towards the suitable direction, but in our case; we're the ones who are controlling the car so we won't need it to rotate on its own or anything, we just need it to avoid the obstacle and stop.

**Comment by FatemaMubarak** [comment]
These two websites show how to avoid obstacles by using ultrasonic sensor that will be attached to a servo motor which is constantly scanning left and right looking for objects in its way.
The websites include tutorials, codes and all libraries we will need.
(1) http://mertarduinotutorial.blogspot.com.eg/2016/12/arduino-project-tutorial-11-obstacle.html
(2) http://www.instructables.com/id/Smartphone-Controlled-Arduino-Rover/

**Comment by EmaMOUKH** [comment]
These websites include 
..first a brief about how we can use avoiding to control the car in a short video then there is an example for the arduino code 
https://www.youtube.com/watch?v=6gf5kKQ0YgQ
https://www.codeproject.com/Articles/126859/RC-Car-Control-Programminghttps://create.arduino.cc/projecthub/Bill_Mougios/arduino-controlled-car-with-hc-sr04-a8e57d

**Comment by EmanmMostafa** [comment]
these links show us how to avoid obstacles using an ultrasonic sensor :  
1- Smartphone Controlled Arduino Rover : http://www.instructables.com/id/Smartphone-Controlled-Arduino-Rover/ ,this link shows the making of an Obstacle Avoiding Rover by using Arduino Nano Board and we can use Arduino UNO, Pro Mini or Micro. 
2- this is a code for ultrasonic sensor for obstacle avoiding using ping library : https://gist.github.com/sdedovic/3391502 
3- In this Arduino project tutorial we will learn how to make obstacle avoiding robot using L298N h-bridge motor driver. Also we will use for this project HC SR04 ultrasonic distance sensor. And we will use NewPing library in the arduino code : http://mertarduinotutorial.blogspot.com.eg/2017/03/arduino-project-tutorial-17-obstacle.html
