### ISSUE TITLE
Line following techniques and code

### ISSUE THREAD

**Issue by ganzourii** [Mokashaa/ASUMobiCarG50#21]
Searching for the best technique of line following ...

**Comment by EmanmMostafa** [comment]
1- In this tutorial, we will make line follower robot. This tutorial involves building a line follower robot with an QTR-8RC Reflectance Sensor Array and here's the link : http://mertarduinotutorial.blogspot.com.eg/2016/12/arduino-project-tutorial-12-line.html 
2- Here's a video explains a line follower code : https://www.youtube.com/watch?v=ZBRbIeaTn2w and this is the code 
[Line follower.docx](https://github.com/Mokashaa/ASUMobiCarG50/files/1869355/Line.follower.docx) 
3- In this link a simple code for line follower using arduino: https://create.arduino.cc/projecthub/16336/line-follower-robot-using-arduino-5f5698 
4- How to make a line follower robot using Arduino and digital ir sensor : http://createyourownrobot.blogspot.com.eg/2016/10/how-to-make-a-line-follower-robot-uisng-digital-ir-sensor-array-6.html

**Comment by Salmahossam97** [comment]
https://youtu.be/YKTGZuTeaU0  video shows the required components for line tracking with the code attached

**Comment by DohaMustafa** [comment]
**Making a line follower from scratch with high stability and performance:** http://www.instructables.com/id/High-performance-Line-follower-Robot/
**Ensuring high speed for a line follower:** https://www.quora.com/How-do-I-ensure-maximum-speed-of-a-line-follower-robot

**Comment by EmaMOUKH** [comment]
1-Here is a link that shows trusted places can get line follower module from it it is available here in Egypt with very good price
https://www.amazon.com/SunFounder-Follower-Infrared-Detection-STM8S105C4/dp/B01HB5YVUG
2-A that has been already tested on a project with schematic
https://create.arduino.cc/projecthub/16336/line-follower-robot-using-arduino-5f5698

**Comment by EmaMOUKH** [comment]
#21
